# Generated by Django 2.1.2 on 2018-10-30 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created',
                 models.DateTimeField(
                     auto_now_add=True,
                     help_text=
                     'The date and time on which the object was created.',
                     verbose_name='Created')),
                ('modified',
                 models.DateTimeField(
                     auto_now=True,
                     help_text=
                     'The date and time on which the object was last modified.',
                     verbose_name='Modified')),
                ('headline',
                 models.CharField(
                     help_text='The headline of the article.',
                     max_length=255,
                     verbose_name='Headline')),
                ('content',
                 models.TextField(
                     help_text='The contents of the article.',
                     verbose_name='Content')),
            ],
            options={
                'ordering': ['created', 'headline'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created',
                 models.DateTimeField(
                     auto_now_add=True,
                     help_text=
                     'The date and time on which the object was created.',
                     verbose_name='Created')),
                ('modified',
                 models.DateTimeField(
                     auto_now=True,
                     help_text=
                     'The date and time on which the object was last modified.',
                     verbose_name='Modified')),
                ('name',
                 models.CharField(
                     help_text='This represents the name of the event.',
                     max_length=255,
                     verbose_name='Event Name')),
                ('description',
                 models.TextField(
                     help_text=
                     'This represents a (short) description of the event.',
                     verbose_name='Event Description')),
                ('start_time',
                 models.DateTimeField(
                     help_text='This is the time when the event starts.',
                     verbose_name='Start Time')),
                ('end_time',
                 models.DateTimeField(
                     help_text='This is the time when the event ends.',
                     verbose_name='End Time')),
            ],
            options={
                'ordering': ['start_time', 'name', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created',
                 models.DateTimeField(
                     auto_now_add=True,
                     help_text=
                     'The date and time on which the object was created.',
                     verbose_name='Created')),
                ('modified',
                 models.DateTimeField(
                     auto_now=True,
                     help_text=
                     'The date and time on which the object was last modified.',
                     verbose_name='Modified')),
                ('payment_ref',
                 models.CharField(
                     help_text='Represents Payment Reference.',
                     max_length=50,
                     verbose_name='Payment Reference')),
                ('extra_info',
                 models.TextField(
                     blank=True,
                     default='',
                     help_text=
                     'Represent extra information related to Payment.',
                     verbose_name='Extra Info')),
            ],
            options={
                'ordering': ['id', 'owner'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('prefix',
                 models.CharField(
                     blank=True,
                     help_text='Your prefix such as Mr. or Ms.',
                     max_length=10,
                     verbose_name='Prefix')),
                ('first_name',
                 models.CharField(
                     help_text='This Represents the Users First Name.',
                     max_length=255,
                     verbose_name='First Name')),
                ('preposition',
                 models.CharField(
                     blank=True,
                     help_text='Your family name preposition.',
                     max_length=255,
                     verbose_name='Preposition')),
                ('last_name',
                 models.CharField(
                     help_text='This Represents the Users Last Name.',
                     max_length=255,
                     verbose_name='Last Name')),
                ('school_id',
                 models.CharField(
                     help_text='This Represents the Users School ID.',
                     max_length=20,
                     unique=True,
                     verbose_name='School ID')),
                ('email',
                 models.EmailField(
                     help_text='This Represents the Users Email.',
                     max_length=254,
                     unique=True,
                     verbose_name='Email')),
                ('phone_number',
                 phonenumber_field.modelfields.PhoneNumberField(
                     blank=True,
                     help_text='This Represents the Users Phone Number.',
                     max_length=128,
                     verbose_name='Phone Number')),
                ('user',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id', 'school_id', 'last_name'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='owner',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to='api.Profile'),
        ),
    ]
