# Generated by Django 2.1.1 on 2018-10-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This represents the name of the event.', max_length=255, verbose_name='Event Name')),
                ('description', models.TextField(help_text='This represents a (short) description of the event.', verbose_name='Event Description')),
                ('start_time', models.DateTimeField(help_text='This is the time when the event starts.', verbose_name='Start Time')),
                ('end_time', models.DateTimeField(help_text='This is the time when the event ends.', verbose_name='End Time')),
            ],
            options={
                'ordering': ['start_time', 'name', 'description'],
            },
        ),
    ]
