# Generated by Django 2.1.1 on 2018-10-03 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time on which the event was created.', verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='The date and time on which the event was last modified.', verbose_name='Modified'),
        ),
    ]
