# Generated by Django 2.1.1 on 2018-10-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181003_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time on which the object was created.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='event',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='The date and time on which the object was last modified.', verbose_name='Modified'),
        ),
    ]
