# Generated by Django 2.1.1 on 2018-10-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181003_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prefix',
            field=models.CharField(blank=True, help_text='Your prefix such as Mr. or Ms.', max_length=10, verbose_name='Prefix'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preposition',
            field=models.CharField(blank=True, help_text='Your family name preposition.', max_length=255, verbose_name='Preposition'),
        ),
    ]
