# Generated by Django 2.1.1 on 2018-10-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181003_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='The date and time on which the object was created.', verbose_name='Created')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='The date and time on which the object was last modified.', verbose_name='Modified')),
                ('headline', models.CharField(help_text='The headline of the article.', max_length=255, verbose_name='Headline')),
                ('content', models.TextField(help_text='The contents of the article.', verbose_name='Content')),
            ],
            options={
                'ordering': ['created_date', 'headline'],
            },
        ),
    ]
